apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-ruoyi-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruoyi-admin
  template:
    metadata:
      labels:
        app: ruoyi-admin
    spec:
      containers:
      - name: ruoyi-admin
        image: localhost:32000/codingsoldier/ruoyi-admin:latest
        imagePullPolicy: Always        
        ports:
        - name: http
          containerPort: 30201
---
apiVersion: v1
kind: Service
metadata:
  name: service-ruoyi-admin
spec:
  selector:
    app: ruoyi-admin
# 使用NodePort类型的Service，绑定service的30201端口到宿主机，以便在物理机上调用
  type: NodePort
  ports:
  - name: http
    port: 30201
    targetPort: 30201
#   暴露端口取值范围是30000-32767
    nodePort: 30201
