apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-ruoyi-app-api-zidian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruoyi-app-api-zidian
  template:
    metadata:
      labels:
        app: ruoyi-app-api-zidian
    spec:
      containers:
      - name: ruoyi-app-api-zidian
        image: localhost:32000/codingsoldier/ruoyi-app-api-zidian:latest
        imagePullPolicy: Always        
        ports:
        - name: http
          containerPort: 30200
---
apiVersion: v1
kind: Service
metadata:
  name: service-ruoyi-app-api-zidian
spec:
  selector:
    app: ruoyi-app-api-zidian
# 使用NodePort类型的Service，绑定service的30200端口到宿主机，以便在物理机上调用
  type: NodePort
  ports:
  - name: http
    port: 30200
    targetPort: 30200
#   暴露端口取值范围是30000-32767
    nodePort: 30200
